root: true
env:
  browser: true
  jest/globals: true
extends:
  - airbnb
  - prettier
plugins:
  - prettier
  - jest
rules:
  prettier/prettier: error
  react/jsx-filename-extension: warn
  react/prefer-stateless-function: warn
  no-use-before-define: warn
  no-param-reassign: warn
