sudo: false

language: node_js

node_js:
  - "8.3.0"

branches:
  only:
    - master

script:
  - yarn run lint
  - yarn run test

notifications:
  email:
    recipients:
      - {{ email }}
    on_success: never
    on_failure: change
